# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Anh-Dung
title-normal: LE
email: leanhdung0205@gmail.com
description:  
url: "https://leanhdung22.github.io" 
author: Anh-Dung LE
street_address: 11 Rue Beaugeard Lancelot
city: Rennes
zip_code: F-35700
country: France
phone: +33 00 00 00 00 00 

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: "pages" # accepts "posts" or "pages" 
tiles-count: 5

# Social settings
500px_url: 
facebook_url: 
github_url: https://github.com/leanhdung22
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/dung-le-793111108/
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 

collections:
  publications:
    output: false
